plugins { id 'com.android.application' }

android {
    signingConfigs {
        debug {
            enableV1Signing = true
            enableV2Signing = true
            enableV3Signing = true
        }
    }

    namespace 'sk.zbierkapohladnic.zberatel'
    compileSdk 36

    defaultConfig {
        applicationId 'sk.zbierkapohladnic.zberatel'
        minSdk 23
        targetSdk 36
        versionCode 4
        versionName '0.4.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
