plugins {
    id 'com.android.application'
}

android {
    namespace 'com.umwear.umwork'
    compileSdk 35

    defaultConfig {
        applicationId 'sk.umwear.umwork.stable'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.2'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
